kind: pipeline
type: docker
name: ${appCode}-front

volumes: # 声明数据卷
  - name: ${appCode}-front # 数据卷名称
    host: # Host Volume
      path: /volumes/drone/volumes/web/${appCode}-front/node_modules # 宿主机目录    #绝对路径
  - name: ssh # 数据卷名称
    host: # Host Volume
      path: /root/.ssh/id_rsa # 宿主机目录    #绝对路径

#发布测试环境，使用scp传输文件夹
steps:
- name: build_test
  image: node:16.0.0
  depends_on: [clone] # 依赖的步骤，
  volumes: # 挂载数据卷
    - name: ${appCode}-front # 数据卷名称
      path: /drone/src/node_modules # 容器内目录 绝对路径
  commands:
    - pwd
    - node -v
    - npm install
    - npm run build -- --mode=development
  when:
    event: [push, pull_request]
    branch: [master, develop, feature/*]
 
- name: deploy_test
  image: appleboy/drone-scp
  depends_on: [build_test]
  volumes: # 挂载数据卷
    - name: ssh # 数据卷名称
      path: /root/.ssh/id_rsa # 容器内目录 绝对路径
  settings:
    host: 192.168.0.85
    port: 3305
    username: root
    rm: true
    key_path: /root/.ssh/id_rsa
    # 来源项目目录
    source: ./dist/*
    strip_components: 1
    # 目标服务器目录
    target: /usr/local/nginx/html/${appCode}-front
  when:
    event: [push, pull_request]
    branch: [master, develop, feature/*]

- name: dingtalk_test
  depends_on: [deploy_test]
  image: lddsb/drone-dingtalk-message
  settings:
    token: ${ding_token}
    secret: ${ding_secret}
    tpl: https://front-1251575231.cos.ap-shanghai.myqcloud.com/dingtalk_tpl_test.md
    type: markdown
  when:
    event: [push, pull_request]
    branch: [master, develop ,feature/*]

- name: build_prd
  image: node:16.0.0
  depends_on: [clone] # 依赖的步骤，
  volumes: # 挂载数据卷
    - name: ${appCode}-front # 数据卷名称
      path: /drone/src/node_modules # 容器内目录 绝对路径
  commands:
    - pwd
    - node -v
    - npm install
    - npm run build -- --mode=production
  when:
    event: [tag]

- name: deploy_prd
  image: appleboy/drone-scp
  depends_on: [build_prd]
  volumes: # 挂载数据卷
    - name: ssh # 数据卷名称
      path: /root/.ssh/id_rsa # 容器内目录 绝对路径
  settings:
    host: 182.254.221.252
    port: 3305
    username: root
    rm: true
    key_path: /root/.ssh/id_rsa
    # 来源项目目录
    source: ./dist/*
    strip_components: 1
    # 目标服务器目录
    target: /usr/local/nginx/html/${appCode}-front
  when:
    event: [tag]

- name: dingtalk_prd
  depends_on: [deploy_prd]
  image: lddsb/drone-dingtalk-message
  settings:
    token: ${ding_token}
    secret: ${ding_secret}
    tpl: https://front-1251575231.cos.ap-shanghai.myqcloud.com/dingtalk_tpl_prd.md
    type: markdown
  when:
    event: [tag]