/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    InfiniteMenu: typeof import('./components/InfiniteMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabsContain: typeof import('./components/TabsContain.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
  }
}
